services:
  servidor_sequencial:
    build:
      context: ./Servidor_sequencial 
    container_name: container-servidor01
    networks:
      minha_rede_customizada:
        ipv4_address: 79.21.0.2 

  cliente_01:
    build:
      context: ./Cliente_01 
    container_name: container-cliente01
    networks:
      minha_rede_customizada:
        ipv4_address: 79.21.0.3 
    depends_on:
      - servidor_sequencial 

  servidor_concorrente:
    build:
      context: ./Servidor_concorrente 
    container_name: container-servidor02
    networks:
      minha_rede_customizada:
        ipv4_address: 79.21.0.4 
  
  cliente_02:
    build:
      context: ./Cliente_02 
    container_name: container-cliente02
    networks:
      minha_rede_customizada:
        ipv4_address: 79.21.0.5 
    depends_on:
      - servidor_concorrente

  cliente_03:
    build:
      context: ./Cliente_03 
    container_name: container-cliente03
    networks:
      minha_rede_customizada:
        ipv4_address: 79.21.0.6 
    depends_on:
      - servidor_concorrente

networks:
  minha_rede_customizada:
    driver: bridge
    ipam: 
      driver: default
      config:
        - subnet: 79.21.0.0/24 